version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - internal-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  halloffame:
    build:
      context: .
      dockerfile: HallOfFame/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BackendDatabase=Host=db;Database=HallOfFrame-db;Username=postgres;Password=postgres
    ports:
        - "8080:8080"
        - "8081:8081"
    volumes:
      - /var/log/HallOfFame:/app/logs

volumes:
  postgres-data: